# Generated by Django 5.1.3 on 2024-11-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_brand_salesrep_vendor_product_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='lightspeedid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sparrownumber',
            field=models.CharField(default=1),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='upc',
            field=models.IntegerField(default=1),
        ),
    ]
