# Generated by Django 5.1.3 on 2024-11-25 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productvariant_lightspeedid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'get_latest_by': 'id'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='items',
        ),
        migrations.AddField(
            model_name='product',
            name='subcat1',
            field=models.ManyToManyField(blank=True, related_name='products', to='inventory.subcategory1'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcat2',
            field=models.ManyToManyField(blank=True, related_name='products', to='inventory.subcategory2'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='rep',
            field=models.ManyToManyField(blank=True, related_name='brands', to='inventory.salesrep'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant'),
        ),
        migrations.AlterField(
            model_name='label',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='lightspeedid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sparrownumber',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='upc',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='vendor',
            field=models.ManyToManyField(blank=True, related_name='sales_reps', to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='subcategory1',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories1', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='sub_category1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories2', to='inventory.subcategory1'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='inventory.category'),
        ),
    ]
